@include(config("options.input_text"),["text_input"=>"nombres","text_label"=>"Nombres"])
@include(config("options.input_text"),["text_input"=>"apellido_paterno","text_label"=>"Apellido Paterno"])
@include(config("options.input_text"),["text_input"=>"apellido_materno","text_label"=>"Apellido Materno"])
@include(config("options.input_text"),["text_input"=>"telefono","text_label"=>"Teléfono"])
@include(config("options.input_text"),["text_input"=>"email","text_label"=>"Email"])
@include(config("options.input_text"),["text_input"=>"pais","text_label"=>"Pais"])